# Example dummy makefile for Verify testbed

.PHONY: all build run clean

all:

build:
	@echo "Build target called."
	touch build

run:
	@echo "Run target called."
	touch run

clean:
	@echo "Clean target called."
	rm -f build run

